# Generated by Django 2.0.10 on 2019-02-11 04:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Emotion')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photoemotion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Photo'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='photos',
            field=models.ManyToManyField(through='core.PhotoEmotion', to='core.Photo'),
        ),
    ]
